apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: metrics-server
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "pods", "pods/metrics"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
roleRef:
  kind: Role
  name: metrics-server
  apiGroup: rbac.authorization.k8s.io

